<!DOCTYPE html>
<html>
<head>
	<title>PES 2018 Tools - MES Modder's Repository</title>
	@include('partials/imports')
</head>
<body>
	@include('partials/navbar')

	@include('partials/float')

	<h1 style="margin-top: 55px;">PES 2018 Tools</h1>
	<div class="container" align="center">
		<ul class="list-inline">
		  <li class="list-inline-item tool-title">PES 2018 Mod Manager</li>
		  <a href="#mod-manager-1.0.0"><li class="list-inline-item tool-version">1.0.0</li></a>
		</ul>
		<ul class="list-inline" style="">
		  <li class="list-inline-item tool-title">PES 2018 Multi Selector Tool</li>
		  <a href="#multi-selector-tool-1.0.0"><li class="list-inline-item tool-version">1.0.0</li></a>
		</ul>
	</div>

	<div class="container-fluid" style="padding: 30px; background-color: white; color: #222222;">
		<div class="row" id="mod-manager-1.0.0" style="margin-bottom: 80px;">
			<div class="col" align="left">
				<h3 style="margin: 0px;">PES 2018 Mod Manager</h3>
			</div>
		</div>
		<!-- 1.0.0 -->
		<div class="row">
			<div class="col-12 col-lg-4">
				<div class="row" style="margin-bottom: 10px;">
					<div class="col">
						<span style="font-weight: bold;">Version 1.0.0 [BETA] - </span>
						<a href="http://yabuilder.com/9Y3N" target="_blank"><button class="download-dropdown">Download</button></a>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Automatically generate DpFileList.bin and creates a backup</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Create and save DpFileList.bin configurations</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Load and edit DpFileList.bin configurations</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Apply a DpFileList.bin configuration directly in PES 2018</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">DpFileList.bin is generated by order of selection</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Set .cpk's priority of generation</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Add .cpk to the exisiting DpFileList.bin</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Choose icons of mods by right-click</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Information about quantity and total size of selected .cpks</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Drag and drop feature</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Double-click on header changes the theme of the window</span>
					</div>
				</div>
			</div>
			<div class="col-12 col-lg-8 my-auto" align="center">
				<img src="https://image.ibb.co/kNCSW9/pes_2018_mod_manager.png" class="tool-preview">
			</div>
		</div>
		<div class="dropdown-divider" id="multi-selector-tool-1.0.0" style="margin-bottom: 80px; margin-top: 80px;"></div>
		<div class="row">
			<div class="col" align="left">
				<h3 style="margin: 0px; padding-top: 30px;">PES 2018 Multi Selector Tool</h3>
			</div>
		</div>
		<!-- 1.0.0 -->
		<div class="row" style="margin-bottom: 80px;">
			<div class="col-12 col-lg-4">
				<div class="row" style="margin-bottom: 10px;">
					<div class="col">
						<span style="font-weight: bold;">Version 1.0.0 - </span>
						<a href="http://agileurbia.com/11cs" target="_blank"><button class="download-dropdown">Download</button></a>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Compatible with DLC 1.0 and 2.0 (selectable)</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Added categories: balls, boots, fonts, press rooms, scoreboards, stadiums, start screens, turf</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Each folder created in main directory is a new category</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">.jpeg or .png file with the same name as the folder is recognized as the category icon</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Every .cpk inside the category folder is added to the list of the respective category</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">.jpeg or .png file with the same name as the .cpk it matches is recognized as the preview to the respective .cpk</span>
					</div>
				</div>
				<div class="row">
					<div class="col" style="margin-bottom: 4px;">
						<span class="tag-new">NEW</span><span style="font-size: 15px;">Clicking on the preview of the .cpk to install triggers the addition of this .cpk to the DpFileList.bin selected</span>
					</div>
				</div>
			</div>
			<div class="col-12 col-lg-8 my-auto" align="center">
				<img src="https://image.ibb.co/eCMPdp/pes_2018_multi_selector_tool.png" class="tool-preview">
			</div>
		</div>
	</div>

	@include('partials/footer')
</body>
</html>